// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	CreateUser(ctx context.Context, in *RequestCreateUser, opts ...grpc.CallOption) (*ResponseCreateUser, error)
	GetUserByID(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*User, error)
	GetUserByUsernameOrEmail(ctx context.Context, in *ParameterUsername, opts ...grpc.CallOption) (*User, error)
	GetUserFromParent(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*ResponseGetFromParent, error)
	ValidateAPIKey(ctx context.Context, in *ParameterAPIKey, opts ...grpc.CallOption) (*ResponseValidateKey, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateUser(ctx context.Context, in *RequestCreateUser, opts ...grpc.CallOption) (*ResponseCreateUser, error) {
	out := new(ResponseCreateUser)
	err := c.cc.Invoke(ctx, "/user.Service/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUserByID(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.Service/GetUserByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUserByUsernameOrEmail(ctx context.Context, in *ParameterUsername, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.Service/GetUserByUsernameOrEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetUserFromParent(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*ResponseGetFromParent, error) {
	out := new(ResponseGetFromParent)
	err := c.cc.Invoke(ctx, "/user.Service/GetUserFromParent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ValidateAPIKey(ctx context.Context, in *ParameterAPIKey, opts ...grpc.CallOption) (*ResponseValidateKey, error) {
	out := new(ResponseValidateKey)
	err := c.cc.Invoke(ctx, "/user.Service/ValidateAPIKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	CreateUser(context.Context, *RequestCreateUser) (*ResponseCreateUser, error)
	GetUserByID(context.Context, *ParameterId) (*User, error)
	GetUserByUsernameOrEmail(context.Context, *ParameterUsername) (*User, error)
	GetUserFromParent(context.Context, *ParameterId) (*ResponseGetFromParent, error)
	ValidateAPIKey(context.Context, *ParameterAPIKey) (*ResponseValidateKey, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) CreateUser(context.Context, *RequestCreateUser) (*ResponseCreateUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedServiceServer) GetUserByID(context.Context, *ParameterId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByID not implemented")
}
func (UnimplementedServiceServer) GetUserByUsernameOrEmail(context.Context, *ParameterUsername) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByUsernameOrEmail not implemented")
}
func (UnimplementedServiceServer) GetUserFromParent(context.Context, *ParameterId) (*ResponseGetFromParent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFromParent not implemented")
}
func (UnimplementedServiceServer) ValidateAPIKey(context.Context, *ParameterAPIKey) (*ResponseValidateKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateAPIKey not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreateUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateUser(ctx, req.(*RequestCreateUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetUserByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/GetUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetUserByID(ctx, req.(*ParameterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetUserByUsernameOrEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterUsername)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetUserByUsernameOrEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/GetUserByUsernameOrEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetUserByUsernameOrEmail(ctx, req.(*ParameterUsername))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetUserFromParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetUserFromParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/GetUserFromParent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetUserFromParent(ctx, req.(*ParameterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ValidateAPIKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterAPIKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ValidateAPIKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/ValidateAPIKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ValidateAPIKey(ctx, req.(*ParameterAPIKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Service_CreateUser_Handler,
		},
		{
			MethodName: "GetUserByID",
			Handler:    _Service_GetUserByID_Handler,
		},
		{
			MethodName: "GetUserByUsernameOrEmail",
			Handler:    _Service_GetUserByUsernameOrEmail_Handler,
		},
		{
			MethodName: "GetUserFromParent",
			Handler:    _Service_GetUserFromParent_Handler,
		},
		{
			MethodName: "ValidateAPIKey",
			Handler:    _Service_ValidateAPIKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models-protos/user/user.proto",
}
