// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	CreateUser(ctx context.Context, in *RequestCreateUser, opts ...grpc.CallOption) (*ResponseCreateUser, error)
	Get(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*User, error)
	GetByUsernameOrEmail(ctx context.Context, in *ParameterUsername, opts ...grpc.CallOption) (*User, error)
	GetFromParent(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*ResponseGetFromParent, error)
	ValidateKey(ctx context.Context, in *ParameterKey, opts ...grpc.CallOption) (*ResponseValidateKey, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateUser(ctx context.Context, in *RequestCreateUser, opts ...grpc.CallOption) (*ResponseCreateUser, error) {
	out := new(ResponseCreateUser)
	err := c.cc.Invoke(ctx, "/user.Service/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Get(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.Service/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetByUsernameOrEmail(ctx context.Context, in *ParameterUsername, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/user.Service/GetByUsernameOrEmail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetFromParent(ctx context.Context, in *ParameterId, opts ...grpc.CallOption) (*ResponseGetFromParent, error) {
	out := new(ResponseGetFromParent)
	err := c.cc.Invoke(ctx, "/user.Service/GetFromParent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) ValidateKey(ctx context.Context, in *ParameterKey, opts ...grpc.CallOption) (*ResponseValidateKey, error) {
	out := new(ResponseValidateKey)
	err := c.cc.Invoke(ctx, "/user.Service/ValidateKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	CreateUser(context.Context, *RequestCreateUser) (*ResponseCreateUser, error)
	Get(context.Context, *ParameterId) (*User, error)
	GetByUsernameOrEmail(context.Context, *ParameterUsername) (*User, error)
	GetFromParent(context.Context, *ParameterId) (*ResponseGetFromParent, error)
	ValidateKey(context.Context, *ParameterKey) (*ResponseValidateKey, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) CreateUser(context.Context, *RequestCreateUser) (*ResponseCreateUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedServiceServer) Get(context.Context, *ParameterId) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServiceServer) GetByUsernameOrEmail(context.Context, *ParameterUsername) (*User, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUsernameOrEmail not implemented")
}
func (UnimplementedServiceServer) GetFromParent(context.Context, *ParameterId) (*ResponseGetFromParent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFromParent not implemented")
}
func (UnimplementedServiceServer) ValidateKey(context.Context, *ParameterKey) (*ResponseValidateKey, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateKey not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreateUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateUser(ctx, req.(*RequestCreateUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Get(ctx, req.(*ParameterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetByUsernameOrEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterUsername)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetByUsernameOrEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/GetByUsernameOrEmail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetByUsernameOrEmail(ctx, req.(*ParameterUsername))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetFromParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetFromParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/GetFromParent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetFromParent(ctx, req.(*ParameterId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_ValidateKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParameterKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).ValidateKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.Service/ValidateKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).ValidateKey(ctx, req.(*ParameterKey))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _Service_CreateUser_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Service_Get_Handler,
		},
		{
			MethodName: "GetByUsernameOrEmail",
			Handler:    _Service_GetByUsernameOrEmail_Handler,
		},
		{
			MethodName: "GetFromParent",
			Handler:    _Service_GetFromParent_Handler,
		},
		{
			MethodName: "ValidateKey",
			Handler:    _Service_ValidateKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "models-protos/user/user.proto",
}
